name: Test
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
        - name: list all lfiles
          run: ls -la
        - name: print workig directory
          run: pwd
        - name: checkout code
          uses: actions/checkout@v4
