name: my first workflow
on: [ push] 
jobs:
  # my-first-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: list all lfiles
  #         run: ls -a
  #       - name: print workig directory
  #         run: pwd
  #       - name: checkout code
  #         uses: actions/checkout@v4
  #       - name: list all files
  #         run: ls -a
  #       - name: print working file contents
  #         run: cat ./.github/workflows/main.yml


  # my-second-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: node current version
  #         run: node -v
  #       - name: update node version
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: '25'
  #       - name: node current version
  #         run: node -v
  #       - name: install react js
  #         run: npm install create-react@latest .

  #  third-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: learinig expressions
  #       run: echo "${{2>1}}"
  #     - run: echo "${{toJson(github)}}"
  #     - run: echo "${{toJson(env)}}"
  #     - run: echo "${{toJson(vars)}}"
  #     - run: echo "${{toJson(secrets)}}"

  # env 

  forth-job:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "sunilkumar"
    steps:
       - run: echo "my name is $MY_NAME"
       - run: echo "my name is ${{env.MY_NAME}}"
       - run: echo "${{vars.MY_FRIST_VAR}}"
       - run: echo ${{secrets.MY_FIRST_SECRETS}}
      
