name: Test
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
        - name: list all lfiles
          run: ls -la
        - name: print workig directory
          run: pwd
        - name: create js file
          run: echo "console.log('Hello, World!');" > hello.js 
        - name: list all files again
          run: ls -la
        - name: run js file
          run: node hello.js 
